### ISSUE TITLE
Make sure the SSH key is added correctly.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/get-gitlab-runner-registration-token#9]
- [x] Find the command in https://github.com/TruCol/Self-host-GitLab-CI-for-GitHub that runs the add ssh-key.
- [ ] Ensure the ssh key with the same description is deleted if it exists already, before adding a new one.
- [x] Ensure the ssh-key "add" button is clicked succesfully.

```
Traceback (most recent call last):
  File "/home/name/miniconda3/envs/get_gitlab_generation_token/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/miniconda3/envs/get_gitlab_generation_token/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/name/git/Col/Self-host-GitLab-CI-for-GitHub/get-gitlab-runner-registration-token/code/project1/src/__main__.py", line 71, in <module>
    ssh_deploy_key_setter = Ssh_deploy_key_setter(
  File "/home/name/git/Col/Self-host-GitLab-CI-for-GitHub/get-gitlab-runner-registration-token/code/project1/src/Ssh_deploy_key_setter.py", line 65, in __init__
    self.fill_in_ssh_key(self.hc, website_controller, self.public_ssh_sha)
  File "/home/name/git/Col/Self-host-GitLab-CI-for-GitHub/get-gitlab-runner-registration-token/code/project1/src/Ssh_deploy_key_setter.py", line 136, in fill_in_ssh_key
    click_element_by_xpath(
  File "/home/name/git/Col/Self-host-GitLab-CI-for-GitHub/get-gitlab-runner-registration-token/code/project1/src/control_website.py", line 251, in click_element_by_xpath
    source_element = website_controller.driver.find_element("xpath",xpath)
  File "/home/name/miniconda3/envs/get_gitlab_generation_token/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/name/miniconda3/envs/get_gitlab_generation_token/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "/home/name/miniconda3/envs/get_gitlab_generation_token/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[6]/div/main/div[2]/div/div/div[2]/div/div/form/button
```

**Comment by a-t-0** [comment]
Done.
